default: &default
  adapter: postgresql
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: <%= ENV['POSTGRES_USER']%>
  username: 'ubuntu'
  password: <%= ENV['POSTGRES_PASSWORD']%>
  host: <%= ENV['POSTGRES_HOST']%>
  template: template0
  encoding: unicode


development:
  <<: *default
  database: capstone_demoapp_development

test:
  <<: *default
  database: capstone_demoapp_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
url: <%= ENV['DATABASE_URL'] %>